[package]
name = "cirrus_egui"
version = "0.2.0"
edition = "2021"

[dependencies]
cirrus_theming = { path = "../theming"}

toml = "0.8.20"
egui = { version = ">=0.31.1" }
serde = { version = "1.0", features = ["derive"] }