[package]
name = "cirrus_egui"
version = "0.1.0"
edition = "2021"

[dependencies]
cirrus_theming = { path = "../theming"}

toml = "0.8"
egui = { version = "0.32" }
serde = { version = "1.0", features = ["derive"] }