[package]
name = "cirrus_updates"
version = "0.1.0"
edition = "2021"

[dependencies]
semver = "1.0"
reqwest = {version = "0.12", features = ["blocking", "json"]}
serde = {version = "1.0", features = ["derive"]}